name: monitoring-system
services:
  myapp:
    build: ./app
    deploy:
      replicas: 3
    expose: 
      - 8080
    volumes:
      - ./app/.env:/etc/express_env/.env
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 4000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - myapp

include:
  - compose.monitoring.yml
